name: Netskope test demo
run-name: Python code scan using Bandit
on:
  push:

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: view
      run: |
        ls -l
        cat requirements.txt
      
    - name: Setting up python 3.0 just to be sure
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: view py version
      run: |
        python3 --version

    - name: Installing dependencies for running snyk
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        
    - name: Setting up dependency scanning using SNYK for python project
      uses: snyk/actions/python-3.6@master
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --json-file-output=snyk_result.json 
