name: Netskope test demo
run-name: Python code scan using Bandit
on:
  pull_request:
    types: [opened]
jobs:
  code-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setting up python 3.0 just to be sure
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Installing dependencies for running bandit and processing results
      run: |
        python -m pip install --upgrade pip
        pip install bandit
        pip install jq

    - name: Running Bandit now on code repository
      run: |
        bandit -r . -f json -o bandit_result.json
        echo "---saving bandit results in a variable named bandit_result for future processing---"
        
    - name: Upload Bandit results in artifacts
      uses: actions/upload-artifact@v4
      with:
        path: bandit_result.json

  sbom-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Setting up SBOM and its reporting
      uses: anchore/sbom-action@v0
      with:
        artifact-name: SBOM_result.json

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@master
 
    - name: Setting up dependency scanning using SNYK for python project
      uses: snyk/actions/python@master
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
        
      
