name: Netskope test demo
run-name: Python code scan using Bandit
on:
  push:

jobs:
  code-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setting up python 3.0 just to be sure
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Installing dependencies for running bandit and processing results
      run: |
        python -m pip install --upgrade pip
        pip install bandit
        pip install jq
        pip install -r requirements.txt

    - name: Run Bandit security scan and save result in a variable
      id: bandit_scan
      run: |
        bandit -r . --exit-zero -f json | tee bandit_result.json
        result=$(cat bandit_result.json)
        echo "::set-output name=bandit_scan::$result"

    - name: Evaluating if any high severity issue is present
      run: |
        result=${{ steps.bandit_scan.outputs.bandit_scan }}
        high_count=$(echo "$result" | jq '.results[] | select(.issue_severity == "HIGH")')
        if [[ -n "$high_count" ]]; then
          echo "High severity vulnerabilities found >>"
          echo "$high_count"
        else
          echo "No high severity vulnerabilities found."
        fi

    - name: Upload Bandit results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: bandit-results
        path: bandit_result.json
        
  sbom-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Setting up SBOM and its reporting
      uses: anchore/sbom-action@v0
      with:
        artifact-name: SBOM_result.json

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: view
      run: |
        ls -l
        cat requirements.txt
      
    - name: Setting up python 3.0 just to be sure
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: view py version
      run: |
        python3 --version

    - name: Installing dependencies for running snyk
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        
    - name: Install npm
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        
    - name: Setting up dependency scanning using SNYK for python project
      run: npm install -g snyk

    - name: Authenticate with Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk scan
      run: snyk test --all-projects 
